export default {
    myProduction : `StartProgram::=Program
Program::=HeadFiles DeclarationStce int main ( ) CompoundStce FunctionBlock
HeadFiles::=# include HeadFile
HeadFile::=<stdio.h>@<stdlib.h>@<math.h>@<ctype.h>@<string.h>@<malloc.h>@<signal.h>@<local.h>@<window.h>
Sentence::=DeclarationStce@ExecuteStce
DeclarationStce::=ValueDeclaration@FunctionDeclaration@ε
ValueDeclaration::=ConstDeclaration@VariableDeclaration
ConstDeclaration::=const IDType ConstDeclarationList
IDType::=boolean@char@int@float@double
ConstDeclarationList::=IDentifier = CONST ConstDeclarationList1
ConstDeclarationList1::=;@, ConstDeclarationList
VariableDeclaration::=IDType ArrayOrNormal
ArrayOrNormal::=VariableDeclarationList@ArrayPostfixes
ArrayPostfixes::=ArrayIDentifier [ ArrayLength ] = ArrayContent ;
ArrayLength::=IntergerPart@ε
ArrayContent::=String@ArrayContentNumber
ArrayContentNumber::={ ArrayContentNumber0 }
ArrayContentNumber0::=IntegerPart ArrayContentNumber1@ε
ArrayContentNumber1::=, IntegerPart ArrayContentNumber2
ArrayContentNumber2::=ArrayContentNumber1@ε
VariableDeclarationList::=SingleVariableDeclaration VariableDeclarationList1
SingleVariableDeclaration::=VARIABLE SingleVariableDeclaration1
SingleVariableDeclaration1::== Expression@ε
VariableDeclarationList1::=;@, VariableDeclarationList
FunctionDeclaration::=FunctionType FuncIDentifier ( FuncDeclareParameterList ) ;
FunctionType::=void@IDType
FuncDeclareParameterList::=FuncDeclareParameter@ε
FuncDeclareParameter::=IDType FuncDeclareParameter1
FuncDeclareParameter1::=, FuncDeclareParameter@ε
ExecuteStce::=DataProcessStce@ControlStce@CompoundStce
DataProcessStce::=AssignStce@FunctionCallStce
AssignStce::=AssignExpr ;
Expression::=ArithmeticExpr@RelationalExpr@AssignExpr
ArithmeticExpr::=Item ArithmeticExpr1
ArithmeticExpr1::=+ Item ArithmeticExpr1@- Item ArithmeticExpr1@ε
Item::=Factor Item1
Item1::=* Factor Item1@/ Factor Item1@% Factor Item1@ε
Factor::=( ArithmeticExpr )@CONST@VARIABLE@FunctionCall
CONST::=Number@Character
VARIABLE::=IDentifier
FunctionCall::=FuncIDentifier ( RealReferenceList )
RealReferenceList::=RealReference@ε
RealReference::=Expression RealReference1
RealReference1::=, RealReference@ε
RelationalExpr::=ArithmeticExpr RelationalOperator ArithmeticExpr
RelationalOperator::=>@<@>=@<=@==@!=
BooleanExpr::=BooleanItem BooleanExpr1
BooleanExpr1::=|| BooleanItem BooleanExpr1@ε
BooleanItem::=BooleanFactor BooleanItem1
BooleanItem1::=&& BooleanFactor BooleanItem1@ε
BooleanFactor::=ArithmeticExpr@RelationalExpr@! BooleanExpr
AssignExpr::=VARIABLE AssignOperator Expression
AssignOperator::==@+=@-=@*=@/=@%=@>>=@<<=@&=@|=
FunctionCallStce::=FunctionCall ;
ControlStce::=IFStce@FORStce@WHILEStce@DOWHILEStce@RETURNStce@BREAKStce@CONTINUEStce
CompoundStce::={ SentenceList }
SentenceList::=NormalStce SentenceList1
SentenceList1::=SentenceList@ε
NormalStce::=ExecuteStce@ValueDeclaration
IFStce::=if ( Expression ) NormalStce
FORStce::=for ( FORFirstExpr Expression1 Expression ) NormalStce
Expression1::=Expression ;
FORFirstExpr::=Expression ;@ValueDeclaration
WHILEStce::=while ( Expression ) NormalStce
DOWHILEStce::=do CompoundStce while ( Expression )
RETURNStce::=return RETURNStce1
RETURNStce1::=;@Expression ;
BREAKStce::=break;
CONTINUEStce::=continue ;
FunctionBlock::=FunctionDefinition FunctionBlock@ε
FunctionDefinition::=FunctionType FuncIDentifier ( FuncDefinitionParameterList ) CompoundStce
FuncDefinitionParameterList::=FuncDefinitionParameter@ε
FuncDefinitionParameter::=IDType IDentifier FuncDefinitionParameter1
FuncDefinitionParameter1::=, FuncDefinitionParameter@ε
PrintfStce::=printf ( String PrintfID ) ;
PrintfID::=, IDentifier PrintfID1
PrintfID1::=PrintfID@ε
ScanfStce::=scanf ( String ScanfID ) ;
ScanfID::=, & IDentifier ScanfID1
ScanfID1::=ScanfID@ε
Number::=IntegerPart@FloatNumber`
}